name: Build

on:
  push:
  pull_request:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test and package the extension
      uses: oncletom/yeswiki-release-action@v1
      with:
        extension-name: yeswiki-extension-publication
        extension-version: ${{ github.ref }}
