on: [push]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test and package the extension
      id: package
      uses: oncletom/yeswiki-build-repo@feature/action
      with:
        extension-name: yeswiki-extension-publication
        extension-version: ${{ github.ref }}

    - name: Assess md5 and archive name
      run: |
        echo "${{ steps.package.outputs.archive-name }} md5sum is ${{ steps.package.outputs.md5sum }}"

    - name: Upload zip file
      if: contains(github.event, 'release')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/${{ steps.package.output.archive-name }}
        asset_name: ${{ steps.package.output.archive-name }}
        asset_content_type: application/zip

    - name: Upload md5 file
      if: contains(github.event, 'release')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/${{ steps.package.output.archive-name }}.md5
        asset_name: ${{ steps.package.output.archive-name }}.md5
        asset_content_type: text/plain
